version: '3'
services:
  nginx:
    build:
      context: ./app/nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - "${LOCAL_STOARGE_PATH}/app/nginx/conf.d:/etc/nginx/conf.d"
      - "${LOCAL_STOARGE_PATH}/app/nginx/ca:/etc/nginx/ca"
      - "${LOCAL_STOARGE_PATH}/app/nginx/my_modules:/etc/nginx/my_modules"
      - "${LOCAL_STOARGE_PATH}/app/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "${LOCAL_STOARGE_PATH}/app/nginx/mime.types:/etc/nginx/mime.types:ro"
      - "${LOCAL_WEB_PATH}:/var/www"
      - "${LOCAL_STOARGE_PATH}/app/secure:/opt/secure:ro"
      - "${LOCAL_STOARGE_PATH}/app/nginx/logs:/var/log/nginx"
      - "${LOCAL_STOARGE_PATH}/app/nginx/letsencrypt:/etc/letsencrypt"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    networks:
      my_dc_net:
        ipv4_address: ${IPV4_PREFIX:-"172.28.1."}11
    ports:
      - 80:80
      - 443:443
      - 8008-8008:8008-8008
    container_name: ${CONTAINER_PRIFIX:-"com_"}nginx
    restart: always
  php:
    build:
      context: ./app/php
      args:
        - PHP_VERSION=${PHP_VERSION}
    environment:
      TZ: ${TIMEZONE}
    volumes:
      - "${LOCAL_WEB_PATH}:/var/www"
      - "${LOCAL_STOARGE_PATH}/app/php/ext:/etc/php/my_ext"
      - "${LOCAL_STOARGE_PATH}/app/php/php.ini:/usr/local/etc/php/php.ini:ro"
      - "${LOCAL_STOARGE_PATH}/app/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro"
      - "${LOCAL_STOARGE_PATH}/app/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro"
      - "${LOCAL_STOARGE_PATH}/app/php/cron.d/prod_demo:/etc/cron.d/prod_demo:ro"
      - "${LOCAL_STOARGE_PATH}/app/php/supervisor:/etc/supervisor"
      - "${LOCAL_STOARGE_PATH}/app/php/logs:/var/log/php"
    ports:
      - 9000:9000
    networks:
      my_dc_net:
        ipv4_address: ${IPV4_PREFIX:-"172.28.1."}12
    container_name: ${CONTAINER_PRIFIX:-"com_"}php
    restart: always
  mysql:
    image: ${MYSQL_VERSION}
    environment:
      - TZ=${TIMEZONE}
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
    ports:
      - 3306:3306
    volumes:
      - "${LOCAL_STOARGE_PATH}/app/mysql/conf.d/my.cnf:/opt/bitnami/mysql/conf/my.cnf:ro"
      - "${LOCAL_STOARGE_PATH}/app/mysql/db:/bitnami/mysql/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    networks:
      my_dc_net:
        ipv4_address: ${IPV4_PREFIX:-"172.28.1."}13
    container_name: ${CONTAINER_PRIFIX:-"com_"}mysql
    restart: always
  redis:
    image: ${REDIS_VERSION}
    environment:
      - TZ=${TIMEZONE}
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_REPLICATION_MODE=master
    volumes:
      - "${LOCAL_STOARGE_PATH}/app/redis/conf.d/redis.conf:/opt/bitnami/redis/etc/redis.conf"
      - "${LOCAL_STOARGE_PATH}/app/redis/db:/bitnami/redis/data"
    networks:
      my_dc_net:
        ipv4_address: ${IPV4_PREFIX:-"172.28.1."}14
    ports:
      - 6379:6379
    sysctls:
      - net.core.somaxconn=1024
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    container_name: ${CONTAINER_PRIFIX:-"com_"}redis
    restart: always
  mongo:
    image: ${MONGO_VERSION}
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=2
      - MONGODB_SYSTEM_LOG_VERBOSITY=3
      - MONGODB_ENABLE_IPV6=no
      - MONGODB_ENABLE_DIRECTORY_PER_DB=no
      - MONGODB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - "${LOCAL_STOARGE_PATH}/app/mongo/config/mongodb.conf:/opt/bitnami/mongodb/conf/mongodb.conf"
      - "${LOCAL_STOARGE_PATH}/app/mongo/db:/bitnami"
      - "mongo_vol:/bitnami"
      - "${LOCAL_STOARGE_PATH}/app/mongo/logs:/opt/bitnami/mongodb/logs"
    networks:
      my_dc_net:
        ipv4_address: ${IPV4_PREFIX:-"172.28.1."}16
    ports:
      - 27017:27017
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    container_name: ${CONTAINER_PRIFIX:-"com_"}mongo
    restart: always
  memcached:
    image: ${MEMCACHED_VERSION}
    environment:
      - MEMCACHED_USERNAME=${MEMCACHED_USERNAME}
      - MEMCACHED_PASSWORD=${MEMCACHED_PASSWORD}
    volumes:
    - "${LOCAL_STOARGE_PATH}/app/memcached/logs:/opt/bitnami/memcached/logs"
    container_name: memcached
    ports:
      - "11211:11211"
    networks:
      my_dc_net:
        ipv4_address: ${IPV4_PREFIX:-"172.28.1."}17
    restart: always
networks:
  my_dc_net:
    name: ${NETWORK_EXT_NAME:-"my_net_dev"}
volumes:
  mongo_vol: